import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Shared/Navbar";
import WorkOutContextProvide from "@/Context/WorkOutContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/Shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-[#1E1E1E] flex flex-col">
        <WorkOutContextProvide>
          <Navbar/>
        <div>
          {children}
        </div>
        <Footer></Footer>
         <ToastContainer />
        </WorkOutContextProvide>

      </body>
    </html>
  );
}
